version: "3.3"

services:
  zookeeper:
    image: bitnami/zookeeper:3.7
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: bitnami/kafka:2
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
  deip-event-proxy:
    image: "$EVENT_PROXY_IMG"
    command: event-proxy --config=/event-proxy.toml
    environment:
      RUST_LOG: "error,librdkafka=error,rdkafka::client=error"
    volumes:
      - "./event-proxy.toml:/event-proxy.toml"
  deip-blockchain-node:
    image: "$BLOCKCHAIN_NODE_IMG"
    command: |
      node-template --dev --tmp --ws-external 
        -lpallet_deip_proposal=debug 
        -lpallet_deip_org=debug 
        -l=txpool=trace,runtime=trace,offchain=trace
    ports:
      - "9944:9944"
  deip-event-proxy-client:
    image: "$EVENT_PROXY_CLIENT_IMG"
    command: event-proxy-client
    environment:
      KAFKA_BOOTSTRAP_SERVERS: "kafka:9092"
    depends_on:
      - kafka

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local
